# Locate the double-precision FFTW libraries used by GALARIO.
#
# Supported components:
#   DOUBLE  - libfftw3 (always required by GALARIO)
#   THREADS - libfftw3_threads
#
# Result variables:
#   FFTW3_FOUND
#   FFTW3_INCLUDE_DIRS
#   FFTW3_INCLUDE_DIR_PARALLEL
#   FFTW3_LIBRARIES

include(FindPackageHandleStandardArgs)

set(_FFTW3_HINT_PREFIXES
  "$ENV{CONDA_PREFIX}"
  "${FFTW3_ROOT}"
  "$ENV{FFTW3_ROOT}"
)

find_path(FFTW3_INCLUDE_DIR
  NAMES fftw3.h
  HINTS ${_FFTW3_HINT_PREFIXES}
  PATH_SUFFIXES include
)

find_library(FFTW3_DOUBLE_LIBRARY
  NAMES fftw3
  HINTS ${_FFTW3_HINT_PREFIXES}
  PATH_SUFFIXES lib lib64
)

set(_FFTW3_REQUIRED_VARS FFTW3_INCLUDE_DIR FFTW3_DOUBLE_LIBRARY)
set(FFTW3_LIBRARIES "${FFTW3_DOUBLE_LIBRARY}")

if("THREADS" IN_LIST FFTW3_FIND_COMPONENTS)
  find_library(FFTW3_THREADS_LIBRARY
    NAMES fftw3_threads
    HINTS ${_FFTW3_HINT_PREFIXES}
    PATH_SUFFIXES lib lib64
  )
  list(APPEND _FFTW3_REQUIRED_VARS FFTW3_THREADS_LIBRARY)
  list(PREPEND FFTW3_LIBRARIES "${FFTW3_THREADS_LIBRARY}")
  set(FFTW3_THREADS_FOUND "${FFTW3_THREADS_LIBRARY}")
endif()

set(FFTW3_DOUBLE_FOUND "${FFTW3_DOUBLE_LIBRARY}")
set(FFTW3_INCLUDE_DIRS "${FFTW3_INCLUDE_DIR}")
set(FFTW3_INCLUDE_DIR_PARALLEL "${FFTW3_INCLUDE_DIR}")

find_package_handle_standard_args(FFTW3
  REQUIRED_VARS ${_FFTW3_REQUIRED_VARS}
  HANDLE_COMPONENTS
)

mark_as_advanced(
  FFTW3_INCLUDE_DIR
  FFTW3_DOUBLE_LIBRARY
  FFTW3_THREADS_LIBRARY
)
